export const publicRoutes = [
  "/",
  "/shop",
  "/coa",
  "/research-library",
  "/my-account",
  "/cart",
  "/checkout",
  "/search",
  "/faq",
  "/support",
  "/contact",
  "/policies/research-use-only",
  "/policies/privacy",
  "/policies/return-refund",
  "/policies/terms",
  "/policies/shipping-returns",
];
